apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jeffliu0/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: jeffliu0/client1
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.js'
            dest: .
    - image: jeffliu0/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
